# Estas son las plataformas de financiamiento soportadas por GitHub
# Descomenta las que apliquen:

# github: [jemgdevp]
# patreon: jemgdevp
# open_collective: neon-trails
# ko_fi: jemgdevp
# tidelift: npm/neon-trails
# community_bridge: neon-trails
# liberapay: jemgdevp
# issuehunt: jemgdevp
# otechie: jemgdevp
# custom: ['https://www.buymeacoffee.com/jemgdevp']

# Neon Trails es un proyecto académico sin fines de lucro.
# Si deseas apoyar, abre un issue con feedback o contribuye con código :)
