blank_issues_enabled: true
contact_links:
  - name: Preguntas o ayuda
    url: https://github.com/jemgdevp/neon-trails/discussions
    about: ¿Tienes una duda? Pregunta en Discussions
  - name: Documentación del proyecto
    url: https://github.com/jemgdevp/neon-trails/tree/master/docs
    about: Revisa la documentación antes de abrir un issue
